version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nutrition_tracker
    volumes:
      - .:/app
      - /app/client/node_modules
    depends_on:
      - db
    networks:
      - app-network
    command: flask run --host=0.0.0.0

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nutrition_tracker
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
